const CITIES = [
  { id: "1", title: "Amsterdam" },
  { id: "2", title: "Ankara" },
  { id: "3", title: "Athens" },
  { id: "4", title: "Bangkok" },
  { id: "5", title: "Beijing" },
  { id: "6", title: "Berlin" },
  { id: "7", title: "Brasilia" },
  { id: "8", title: "Brussels" },
  { id: "9", title: "Budapest" },
  { id: "10", title: "Buenos Aires" },
  { id: "11", title: "Cairo" },
  { id: "12", title: "Canberra" },
  { id: "13", title: "Copenhagen" },
  { id: "14", title: "Dublin" },
  { id: "15", title: "Hanoi" },
  { id: "16", title: "Helsinki" },
  { id: "17", title: "Islamabad" },
  { id: "18", title: "Jakarta" },
  { id: "19", title: "Lisbon" },
  { id: "20", title: "London" },
  { id: "21", title: "Madrid" },
  { id: "22", title: "Manila" },
  { id: "23", title: "Mexico City" },
  { id: "24", title: "Minsk" },
  { id: "25", title: "Moscow" },
  { id: "26", title: "Nairobi" },
  { id: "27", title: "New Delhi" },
  { id: "28", title: "Oslo" },
  { id: "29", title: "Ottawa" },
  { id: "30", title: "Paris" },
  { id: "31", title: "Prague" },
  { id: "32", title: "Reykjavik" },
  { id: "33", title: "Rome" },
  { id: "34", title: "Seoul" },
  { id: "35", title: "Singapore" },
  { id: "36", title: "Stockholm" },
  { id: "37", title: "Tokyo" },
  { id: "38", title: "Vienna" },
  { id: "39", title: "Warsaw" },
  { id: "40", title: "Washington" },
];

export default CITIES;
